# Generated by Django 2.0 on 2019-11-09 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_eb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeeventbriteevent',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='fakeeventbriteevent',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='fakeeventbriteevent',
            name='organization_id',
            field=models.BigIntegerField(default=9999999),
        ),
    ]
