# Generated by Django 2.2 on 2019-11-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_eb', '0003_fakeeventbriteevent_duration_specfier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeeventbriteevent',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
